---
sudo: required
dist: trusty

language:
    - python

python:
  - "3.4"

addons:
 apt:
   packages:
   - gcc-avr
   - binutils-avr
   - avr-libc
   - arduino
   - cmake

script: tools/compile_test.py
