---
sudo: required
dist: trusty

language:
    - python

cache:
    - ccache

python:
  - "3.4"

addons:
 apt:
   packages:
   - gcc-avr
   - binutils-avr
   - avr-libc
   - arduino
   - cmake
   - ccache

script: tools/compile_test.py
